### ISSUE TITLE
[gmp_rational] realloc() issue

### ISSUE THREAD

**Issue by 0152la** [PollyLabs/library-metamorphic-testing#9]
The attached test case yields a `realloc` related error message, along with a fairly large backtrace: `*** Error in ./test_run_199430313922593636': realloc(): invalid old size: 0x00007fff7e0168a0 ***`

[realloc.zip](https://github.com/PollyLabs/library-metamorphic-testing/files/2988028/realloc.zip)

**Comment by diorga** [comment]
I think it should be fixed by the previous bug fix. I am not completely sure though.
